// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLLMSignIn() {
  return window['go']['main']['App']['CancelLLMSignIn']();
}

export function ChangeTargetFolder(arg1) {
  return window['go']['main']['App']['ChangeTargetFolder'](arg1);
}

export function CheckGitInstallation() {
  return window['go']['main']['App']['CheckGitInstallation']();
}

export function ChooseDirectory(arg1) {
  return window['go']['main']['App']['ChooseDirectory'](arg1);
}

export function ChooseLegacy() {
  return window['go']['main']['App']['ChooseLegacy']();
}

export function ChooseRulePackage() {
  return window['go']['main']['App']['ChooseRulePackage']();
}

export function ClearLLMConnectionCredential(arg1) {
  return window['go']['main']['App']['ClearLLMConnectionCredential'](arg1);
}

export function CloseRule() {
  return window['go']['main']['App']['CloseRule']();
}

export function CreateDemoProject(arg1) {
  return window['go']['main']['App']['CreateDemoProject'](arg1);
}

export function CreateDemoWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateDemoWorkspace'](arg1, arg2);
}

export function CreateRule(arg1) {
  return window['go']['main']['App']['CreateRule'](arg1);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteLLMConnection(arg1) {
  return window['go']['main']['App']['DeleteLLMConnection'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DiscardFileChanges(arg1) {
  return window['go']['main']['App']['DiscardFileChanges'](arg1);
}

export function DuplicateWorkspace(arg1) {
  return window['go']['main']['App']['DuplicateWorkspace'](arg1);
}

export function ExportExecutionReport(arg1) {
  return window['go']['main']['App']['ExportExecutionReport'](arg1);
}

export function ExportReport() {
  return window['go']['main']['App']['ExportReport']();
}

export function ExportRulePackage() {
  return window['go']['main']['App']['ExportRulePackage']();
}

export function GetExecutionFileDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetExecutionFileDetail'](arg1, arg2, arg3);
}

export function GetExecutionRun(arg1) {
  return window['go']['main']['App']['GetExecutionRun'](arg1);
}

export function GetFileDetail(arg1, arg2) {
  return window['go']['main']['App']['GetFileDetail'](arg1, arg2);
}

export function GetResultPublicationFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResultPublicationFileDiff'](arg1, arg2, arg3);
}

export function GetResultPublicationPreview() {
  return window['go']['main']['App']['GetResultPublicationPreview']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportRulePackage(arg1, arg2) {
  return window['go']['main']['App']['ImportRulePackage'](arg1, arg2);
}

export function ListTargetFiles(arg1, arg2) {
  return window['go']['main']['App']['ListTargetFiles'](arg1, arg2);
}

export function OpenGitInstallGuide() {
  return window['go']['main']['App']['OpenGitInstallGuide']();
}

export function OpenRule(arg1) {
  return window['go']['main']['App']['OpenRule'](arg1);
}

export function OpenWorktree() {
  return window['go']['main']['App']['OpenWorktree']();
}

export function PublishResults(arg1) {
  return window['go']['main']['App']['PublishResults'](arg1);
}

export function ReadExecutionFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadExecutionFile'](arg1, arg2, arg3);
}

export function ReadRule(arg1) {
  return window['go']['main']['App']['ReadRule'](arg1);
}

export function ReadTargetFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadTargetFile'](arg1, arg2, arg3);
}

export function RenameWorkspace(arg1) {
  return window['go']['main']['App']['RenameWorkspace'](arg1);
}

export function RetryTasks(arg1) {
  return window['go']['main']['App']['RetryTasks'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveLLMConnection(arg1) {
  return window['go']['main']['App']['SaveLLMConnection'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function SaveRules(arg1) {
  return window['go']['main']['App']['SaveRules'](arg1);
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}

export function SelectLLMConnection(arg1) {
  return window['go']['main']['App']['SelectLLMConnection'](arg1);
}

export function SelectWorkspace(arg1) {
  return window['go']['main']['App']['SelectWorkspace'](arg1);
}

export function SetTaskSelection(arg1) {
  return window['go']['main']['App']['SetTaskSelection'](arg1);
}

export function SignInLLMConnection(arg1) {
  return window['go']['main']['App']['SignInLLMConnection'](arg1);
}

export function SignOutLLMConnection(arg1) {
  return window['go']['main']['App']['SignOutLLMConnection'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}

export function ValidateTargetFolder(arg1) {
  return window['go']['main']['App']['ValidateTargetFolder'](arg1);
}
