// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CancelLLMSignIn():Promise<void>;

export function ChangeTargetFolder(arg1:string):Promise<model.State>;

export function CheckGitInstallation():Promise<model.GitInstallation>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseLegacy():Promise<string>;

export function ChooseRulePackage():Promise<string>;

export function ClearLLMConnectionCredential(arg1:string):Promise<model.State>;

export function CloseRule():Promise<void>;

export function CreateDemoProject(arg1:string):Promise<string>;

export function CreateDemoWorkspace(arg1:string,arg2:string):Promise<model.State>;

export function CreateRule(arg1:model.RuleEdit):Promise<model.State>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<model.State>;

export function DeleteLLMConnection(arg1:string):Promise<model.State>;

export function DeleteRule(arg1:string):Promise<model.State>;

export function DeleteWorkspace(arg1:string):Promise<model.State>;

export function DiscardFileChanges(arg1:string):Promise<model.State>;

export function DuplicateWorkspace(arg1:string):Promise<model.State>;

export function ExportExecutionReport(arg1:string):Promise<string>;

export function ExportReport():Promise<string>;

export function ExportRulePackage():Promise<string>;

export function GetExecutionFileDetail(arg1:string,arg2:string,arg3:number):Promise<model.FileDetail>;

export function GetExecutionRun(arg1:string):Promise<model.ExecutionRunResult>;

export function GetFileDetail(arg1:string,arg2:number):Promise<model.FileDetail>;

export function GetResultPublicationFileDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetResultPublicationPreview():Promise<model.ResultPublicationPreview>;

export function GetState():Promise<model.State>;

export function ImportRulePackage(arg1:string,arg2:string):Promise<model.State>;

export function ListTargetFiles(arg1:string,arg2:string):Promise<model.TargetFileList>;

export function OpenGitInstallGuide():Promise<void>;

export function OpenRule(arg1:string):Promise<model.RuleEditor>;

export function OpenWorktree():Promise<void>;

export function PublishResults(arg1:model.PublishResultsRequest):Promise<model.ResultPublication>;

export function ReadExecutionFile(arg1:string,arg2:string,arg3:string):Promise<model.TargetFileContent>;

export function ReadRule(arg1:string):Promise<model.Rule>;

export function ReadTargetFile(arg1:string,arg2:string,arg3:string):Promise<model.TargetFileContent>;

export function RenameWorkspace(arg1:string):Promise<model.State>;

export function RetryTasks(arg1:Array<string>):Promise<model.State>;

export function SaveConfig(arg1:model.Config):Promise<model.State>;

export function SaveLLMConnection(arg1:model.LLMConnection):Promise<model.State>;

export function SaveRule(arg1:model.RuleEdit):Promise<model.State>;

export function SaveRules(arg1:Array<model.RuleEdit>):Promise<model.State>;

export function Scan():Promise<model.State>;

export function SelectLLMConnection(arg1:string):Promise<model.State>;

export function SelectWorkspace(arg1:string):Promise<model.State>;

export function SetTaskSelection(arg1:Array<string>):Promise<model.State>;

export function SignInLLMConnection(arg1:string):Promise<model.State>;

export function SignOutLLMConnection(arg1:string):Promise<model.State>;

export function Start(arg1:number):Promise<void>;

export function Stop():Promise<void>;

export function TestConnection():Promise<string>;

export function TestLLMConnection(arg1:string):Promise<string>;

export function ValidateTargetFolder(arg1:string):Promise<string>;
